"""gercek FCR: customer_ref, is_repeat, repeat_of_id

Revision ID: 9c5a1ea9766b
Revises: 
Create Date: 2026-07-15 15:54:55.386856
"""
from alembic import op
import sqlalchemy as sa


revision = '9c5a1ea9766b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Gercek FCR icin musteri referansi + tekrar arama alanlari.

    Not: is_repeat NOT NULL oldugu icin MEVCUT satirlarin bir degeri olmali —
    server_default='false' ile eklenir (Alembic'in autogenerate ciktisinda bu
    yoktu, "please adjust" uyarisi tam olarak bunu kastediyor). Kolon dolduktan
    sonra default kaldirilir: uygulama degeri her zaman acikca yazar.
    """
    op.add_column('calls', sa.Column('customer_ref', sa.String(length=128), nullable=True))
    op.add_column(
        'calls',
        sa.Column('is_repeat', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('calls', sa.Column('repeat_of_id', sa.Integer(), nullable=True))
    op.alter_column('calls', 'is_repeat', server_default=None)
    op.create_index(op.f('ix_calls_customer_ref'), 'calls', ['customer_ref'], unique=False)
    op.create_index(op.f('ix_calls_is_repeat'), 'calls', ['is_repeat'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_is_repeat'), table_name='calls')
    op.drop_index(op.f('ix_calls_customer_ref'), table_name='calls')
    op.drop_column('calls', 'repeat_of_id')
    op.drop_column('calls', 'is_repeat')
    op.drop_column('calls', 'customer_ref')
    # ### end Alembic commands ###
